/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "tableflip.dev/maths/pkg/apis/maths/v1alpha1"
	scheme "tableflip.dev/maths/pkg/client/clientset/versioned/scheme"
)

// SubtractsGetter has a method to return a SubtractInterface.
// A group's client should implement this interface.
type SubtractsGetter interface {
	Subtracts(namespace string) SubtractInterface
}

// SubtractInterface has methods to work with Subtract resources.
type SubtractInterface interface {
	Create(ctx context.Context, subtract *v1alpha1.Subtract, opts v1.CreateOptions) (*v1alpha1.Subtract, error)
	Update(ctx context.Context, subtract *v1alpha1.Subtract, opts v1.UpdateOptions) (*v1alpha1.Subtract, error)
	UpdateStatus(ctx context.Context, subtract *v1alpha1.Subtract, opts v1.UpdateOptions) (*v1alpha1.Subtract, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Subtract, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.SubtractList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Subtract, err error)
	SubtractExpansion
}

// subtracts implements SubtractInterface
type subtracts struct {
	client rest.Interface
	ns     string
}

// newSubtracts returns a Subtracts
func newSubtracts(c *MathsV1alpha1Client, namespace string) *subtracts {
	return &subtracts{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the subtract, and returns the corresponding subtract object, and an error if there is any.
func (c *subtracts) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Subtract, err error) {
	result = &v1alpha1.Subtract{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subtracts").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Subtracts that match those selectors.
func (c *subtracts) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SubtractList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.SubtractList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("subtracts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested subtracts.
func (c *subtracts) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("subtracts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a subtract and creates it.  Returns the server's representation of the subtract, and an error, if there is any.
func (c *subtracts) Create(ctx context.Context, subtract *v1alpha1.Subtract, opts v1.CreateOptions) (result *v1alpha1.Subtract, err error) {
	result = &v1alpha1.Subtract{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("subtracts").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subtract).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a subtract and updates it. Returns the server's representation of the subtract, and an error, if there is any.
func (c *subtracts) Update(ctx context.Context, subtract *v1alpha1.Subtract, opts v1.UpdateOptions) (result *v1alpha1.Subtract, err error) {
	result = &v1alpha1.Subtract{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subtracts").
		Name(subtract.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subtract).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *subtracts) UpdateStatus(ctx context.Context, subtract *v1alpha1.Subtract, opts v1.UpdateOptions) (result *v1alpha1.Subtract, err error) {
	result = &v1alpha1.Subtract{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("subtracts").
		Name(subtract.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(subtract).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the subtract and deletes it. Returns an error if one occurs.
func (c *subtracts) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subtracts").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *subtracts) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("subtracts").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched subtract.
func (c *subtracts) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Subtract, err error) {
	result = &v1alpha1.Subtract{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("subtracts").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
