/*
Copyright 2021 The Knative Authors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	mathsv1alpha1 "tableflip.dev/maths/pkg/apis/maths/v1alpha1"
	versioned "tableflip.dev/maths/pkg/client/clientset/versioned"
	internalinterfaces "tableflip.dev/maths/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "tableflip.dev/maths/pkg/client/listers/maths/v1alpha1"
)

// AddInformer provides access to a shared informer and lister for
// Adds.
type AddInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AddLister
}

type addInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAddInformer constructs a new informer for Add type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAddInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAddInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAddInformer constructs a new informer for Add type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAddInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MathsV1alpha1().Adds(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MathsV1alpha1().Adds(namespace).Watch(context.TODO(), options)
			},
		},
		&mathsv1alpha1.Add{},
		resyncPeriod,
		indexers,
	)
}

func (f *addInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAddInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *addInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&mathsv1alpha1.Add{}, f.defaultInformer)
}

func (f *addInformer) Lister() v1alpha1.AddLister {
	return v1alpha1.NewAddLister(f.Informer().GetIndexer())
}
